# Generated by Django 2.2.12 on 2020-08-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useripdetails',
            name='ip_address',
            field=models.CharField(max_length=100),
        ),
    ]
