# Generated by Django 2.2.12 on 2020-08-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogist', '0002_auto_20200816_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useripdetails',
            name='with_mask_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='useripdetails',
            name='without_mask_count',
            field=models.IntegerField(null=True),
        ),
    ]
