# Generated by Django 2.2.12 on 2020-08-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogist', '0003_auto_20200816_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useripdetails',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
