# Generated by Django 2.2.12 on 2020-08-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hogist', '0004_auto_20200816_2230'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useripdetails',
            table='user_ipdetails',
        ),
    ]
