# Generated by Django 2.2.12 on 2020-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogist', '0005_auto_20200818_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='useripdetails',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
