# Generated by Django 2.2.12 on 2020-08-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogist', '0006_useripdetails_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='useripdetails',
            name='social_dis',
            field=models.IntegerField(null=True),
        ),
    ]
