# Generated by Django 2.2.12 on 2020-08-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extenduserdetails',
            options={'managed': False},
        ),
    ]
